spring:
  application:
    name: finance-api

  frontend:
    url: ${FRONTEND_URL:http://localhost:5173}

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/finance_control}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_secret_key:12345678}
