import { useEffect, useMemo, useState } from "react";
import { api } from "../api/client";
import type { Summary } from "../types";
import { Button } from "../components/ui";

export function SummaryPage() {
  const [summaries, setSummaries] = useState<Summary[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);

  const loadSummaries = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await api.get<Summary[]>("/summary");
      setSummaries(res.data);
    } catch (err: unknown) {
      console.error(err);
      setError("Could not load summaries.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void loadSummaries();
  }, []);

  const handleGenerate = async () => {
    setGenerating(true);
    setError(null);
    try {
      await api.post("/summary/generate/");
      await loadSummaries();
    } catch (err: unknown) {
      console.error(err);
      setError("Could not generate summary for current month.");
    } finally {
      setGenerating(false);
    }
  };

  const rows = useMemo(
    () =>
      [...summaries].sort((a, b) => (a.initialDate < b.initialDate ? 1 : -1)),
    [summaries]
  );

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-semibold text-slate-100">Summary</h2>
          <p className="text-xs text-slate-400 mt-1">Monthly summaries generated by the backend.</p>
        </div>
        <Button onClick={handleGenerate} disabled={generating}>
          {generating ? "Generating..." : "Generate current month summary"}
        </Button>
      </div>

      {error && <p className="text-xs text-expense">{error}</p>}

      <div className="overflow-x-auto rounded-xl border border-slate-800 bg-slate-900/60">
        <table className="min-w-full text-left text-xs">
          <thead className="border-b border-slate-800 bg-slate-900/80">
            <tr>
              <th className="px-4 py-2 font-medium text-slate-400">Period</th>
              <th className="px-4 py-2 font-medium text-slate-400">Income</th>
              <th className="px-4 py-2 font-medium text-slate-400">Expense</th>
              <th className="px-4 py-2 font-medium text-slate-400">Balance</th>
              <th className="px-4 py-2 font-medium text-slate-400">Transactions</th>
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr>
                <td colSpan={5} className="px-4 py-6 text-center text-slate-400">
                  Loading summaries...
                </td>
              </tr>
            ) : rows.length === 0 ? (
              <tr>
                <td colSpan={5} className="px-4 py-6 text-center text-slate-400">
                  No summaries yet. Generate one to get started.
                </td>
              </tr>
            ) : (
              rows.map((s) => (
                <tr key={s.id} className="border-t border-slate-800">
                  <td className="px-4 py-2 text-slate-200">
                    {new Date(s.initialDate).toLocaleDateString()} –{" "}
                    {new Date(s.finalDate).toLocaleDateString()}
                  </td>
                  <td className="px-4 py-2 text-income font-medium">
                    {s.totalIncome.toLocaleString("en-US", { style: "currency", currency: "USD" })}
                  </td>
                  <td className="px-4 py-2 text-expense font-medium">
                    {s.totalExpense.toLocaleString("en-US", { style: "currency", currency: "USD" })}
                  </td>
                  <td
                    className={`px-4 py-2 font-semibold ${
                      s.balance >= 0 ? "text-income" : "text-expense"
                    }`}
                  >
                    {s.balance.toLocaleString("en-US", { style: "currency", currency: "USD" })}
                  </td>
                  <td className="px-4 py-2 text-slate-200">{s.totalTransactions}</td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}

