import { useEffect, useMemo, useState } from "react";
import axios from "axios";
import { api } from "../api/client";
import type { Summary } from "../types";
import { Button } from "../components/ui";

export function SummaryPage() {
  const [summaries, setSummaries] = useState<Summary[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [deletingId, setDeletingId] = useState<number | null>(null);

  const loadSummaries = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await api.get<Summary[]>("/summary");
      setSummaries(res.data);
    } catch (err: unknown) {
      console.error(err);
      setError("Could not load summaries.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void loadSummaries();
  }, []);

  const handleGenerate = async () => {
    setGenerating(true);
    setError(null);
    try {
      await api.post("/summary/generate/");
      await loadSummaries();
    } catch (err: unknown) {
      console.error(err);
      if (axios.isAxiosError(err) && err.response?.status === 409) {
        setError("A summary already exists for this month. Delete it first to regenerate.");
      } else {
        setError("Could not generate summary for current month.");
      }
    } finally {
      setGenerating(false);
    }
  };

  const handleDelete = async (id: number) => {
    const confirmed = window.confirm("Delete this summary?");
    if (!confirmed) return;

    setDeletingId(id);
    setError(null);
    try {
      await api.delete(`/summary/${id}`);
      await loadSummaries();
    } catch (err: unknown) {
      console.error(err);
      setError("Could not delete summary.");
    } finally {
      setDeletingId(null);
    }
  };

  const rows = useMemo(
    () =>
      [...summaries].sort((a, b) => (a.initialDate < b.initialDate ? 1 : -1)),
    [summaries]
  );

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h2 className="text-xl font-semibold text-slate-100">Summary</h2>
          <p className="text-xs text-slate-400 mt-1">Monthly summaries generated by the backend.</p>
        </div>
        <Button onClick={handleGenerate} disabled={generating}>
          {generating ? "Generating..." : "Generate current month summary"}
        </Button>
      </div>

      {error && <p className="text-xs text-expense">{error}</p>}

      <div className="hidden md:block overflow-x-auto rounded-xl border border-slate-800 bg-slate-900/60">
        <table className="min-w-full text-left text-xs">
          <thead className="border-b border-slate-800 bg-slate-900/80">
            <tr>
              <th className="px-4 py-2 font-medium text-slate-400">Period</th>
              <th className="px-4 py-2 font-medium text-slate-400">Income</th>
              <th className="px-4 py-2 font-medium text-slate-400">Expense</th>
              <th className="px-4 py-2 font-medium text-slate-400">Balance</th>
              <th className="px-4 py-2 font-medium text-slate-400">Transactions</th>
              <th className="px-4 py-2 font-medium text-slate-400 text-right">Actions</th>
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr>
                <td colSpan={6} className="px-4 py-6 text-center text-slate-400">
                  Loading summaries...
                </td>
              </tr>
            ) : rows.length === 0 ? (
              <tr>
                <td colSpan={6} className="px-4 py-6 text-center text-slate-400">
                  No summaries yet. Generate one to get started.
                </td>
              </tr>
            ) : (
              rows.map((s) => (
                <tr key={s.id} className="border-t border-slate-800">
                  <td className="px-4 py-2 text-slate-200">
                    {new Date(s.initialDate).toLocaleDateString()} –{" "}
                    {new Date(s.finalDate).toLocaleDateString()}
                  </td>
                  <td className="px-4 py-2 text-income font-medium">
                    {s.totalIncome.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}
                  </td>
                  <td className="px-4 py-2 text-expense font-medium">
                    {s.totalExpense.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}
                  </td>
                  <td
                    className={`px-4 py-2 font-semibold ${
                      s.balance >= 0 ? "text-income" : "text-expense"
                    }`}
                  >
                    {s.balance.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}
                  </td>
                  <td className="px-4 py-2 text-slate-200">{s.totalTransactions}</td>
                  <td className="px-4 py-2 text-right">
                    <Button
                      type="button"
                      variant="ghost"
                      className="text-xs px-2 py-1 text-expense hover:bg-slate-800"
                      onClick={() => void handleDelete(s.id)}
                      disabled={deletingId === s.id}
                    >
                      {deletingId === s.id ? "Deleting..." : "Delete"}
                    </Button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      <div className="md:hidden space-y-3">
        {loading ? (
          <div className="rounded-xl border border-slate-800 bg-slate-900/60 px-4 py-6 text-center text-slate-400 text-sm">
            Loading summaries...
          </div>
        ) : rows.length === 0 ? (
          <div className="rounded-xl border border-slate-800 bg-slate-900/60 px-4 py-6 text-center text-slate-400 text-sm">
            No summaries yet. Generate one to get started.
          </div>
        ) : (
          rows.map((s) => (
            <div key={s.id} className="rounded-xl border border-slate-800 bg-slate-900/60 p-4 space-y-2">
              <p className="text-xs text-slate-400">
                {new Date(s.initialDate).toLocaleDateString()} - {new Date(s.finalDate).toLocaleDateString()}
              </p>
              <p className="text-sm text-income font-medium">
                Income: {s.totalIncome.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}
              </p>
              <p className="text-sm text-expense font-medium">
                Expense: {s.totalExpense.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}
              </p>
              <p className={`text-sm font-semibold ${s.balance >= 0 ? "text-income" : "text-expense"}`}>
                Balance: {s.balance.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}
              </p>
              <p className="text-xs text-slate-300">Transactions: {s.totalTransactions}</p>
              <Button
                type="button"
                variant="ghost"
                className="w-full text-expense hover:bg-slate-800"
                onClick={() => void handleDelete(s.id)}
                disabled={deletingId === s.id}
              >
                {deletingId === s.id ? "Deleting..." : "Delete"}
              </Button>
            </div>
          ))
        )}
      </div>
    </div>
  );
}

